// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.17.2
// source: proto.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Addtwo_Add_FullMethodName = "/api.addtwo/add"
)

// AddtwoClient is the client API for Addtwo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddtwoClient interface {
	Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type addtwoClient struct {
	cc grpc.ClientConnInterface
}

func NewAddtwoClient(cc grpc.ClientConnInterface) AddtwoClient {
	return &addtwoClient{cc}
}

func (c *addtwoClient) Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Addtwo_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddtwoServer is the server API for Addtwo service.
// All implementations must embed UnimplementedAddtwoServer
// for forward compatibility.
type AddtwoServer interface {
	Add(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAddtwoServer()
}

// UnimplementedAddtwoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddtwoServer struct{}

func (UnimplementedAddtwoServer) Add(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAddtwoServer) mustEmbedUnimplementedAddtwoServer() {}
func (UnimplementedAddtwoServer) testEmbeddedByValue()                {}

// UnsafeAddtwoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddtwoServer will
// result in compilation errors.
type UnsafeAddtwoServer interface {
	mustEmbedUnimplementedAddtwoServer()
}

func RegisterAddtwoServer(s grpc.ServiceRegistrar, srv AddtwoServer) {
	// If the following call pancis, it indicates UnimplementedAddtwoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Addtwo_ServiceDesc, srv)
}

func _Addtwo_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddtwoServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Addtwo_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddtwoServer).Add(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Addtwo_ServiceDesc is the grpc.ServiceDesc for Addtwo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Addtwo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.addtwo",
	HandlerType: (*AddtwoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _Addtwo_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
